# This source file is part of the Swift.org open source project
#
# Copyright (c) 2021 Apple Inc. and the Swift project authors
# Licensed under Apache License v2.0 with Runtime Library Exception
#
# See http://swift.org/LICENSE.txt for license information
# See http://swift.org/CONTRIBUTORS.txt for Swift project authors

version: "2"

services:

  docker-setup:
    image: centos8-rpm-builder
    build:
      context: .
      dockerfile: Dockerfile

  common: &common
    image: centos8-rpm-builder
    depends_on: [docker-setup]
    volumes:
      - .:/code:z
      - ./.output:/output:z
    working_dir: /code
    cap_drop:
      - CAP_NET_RAW
      - CAP_NET_BIND_SERVICE

  build:
    <<: *common
    command: /bin/bash -cl "./build_rpm.sh"

  shell:
    <<: *common
    entrypoint: /bin/bash -l
